namespace SharpScript.Subclassing;

/// <summary>
/// Engine-agnostic UFUNCTION specifier bits supplied by the C# layer.
/// <br/> See: SharpScript/Private/Subclassing/SsFunctionSpecifiers.h ESsFunctionSpecifier 
/// </summary>
[Flags]
public enum FuncSpecs : UInt64
{
	// /// <summary>
	// /// This function is designed to be overridden by a blueprint.  Do not provide a body for this function;
	// /// the autogenerated code will include a thunk that calls ProcessEvent to execute the overridden body.
	// /// </summary>
	// BlueprintImplementableEvent = 1 << 0,

	/// <summary>
	/// This function is designed to be overridden by a blueprint, but also has a native (C#) implementation.
	/// The C# side writes a single method whose body is the default implementation; source-level calls to it
	/// are redirected (via C# interceptors) to a virtual-dispatch entry that resolves any blueprint override.
	/// </summary>
	BlueprintEvent = 1 << 1,

	// /// <summary>
	// /// This function is sealed and cannot be overridden in subclasses.
	// /// It is only a valid keyword for events; declare other methods as static or final to indicate that they are sealed.
	// /// </summary>
	// SealedEvent = 1 << 2,

	/// <summary>
	/// This function is executable from the command line.
	/// </summary>
	Exec = 1 << 3,

	// /// <summary>
	// /// This function is replicated, and executed on servers.  Provide a body named [FunctionName]_Implementation instead of [FunctionName];
	// /// the autogenerated code will include a thunk that calls the implementation method when necessary.
	// /// </summary>
	// Server = 1 << 4,

	// /// <summary>
	// /// This function is replicated, and executed on clients.  Provide a body named [FunctionName]_Implementation instead of [FunctionName];
	// /// the autogenerated code will include a thunk that calls the implementation method when necessary.
	// /// </summary>
	// Client = 1 << 5,

	// /// <summary>
	// /// This function is both executed locally on the server and replicated to all clients, regardless of the Actor's NetOwner
	// /// </summary>
	// NetMulticast = 1 << 6,

	// /// <summary>
	// /// Replication of calls to this function should be done on a reliable channel.
	// /// Only valid when used in conjunction with Client, Server, or NetMulticast
	// /// </summary>
	// Reliable = 1 << 7,

	// /// <summary>
	// /// Replication of calls to this function can be done on an unreliable channel.
	// /// Only valid when used in conjunction with Client, Server, or NetMulticast
	// /// </summary>
	// Unreliable = 1 << 8,

	/// <summary>
	/// This function fulfills a contract of producing no side effects, and additionally implies BlueprintCallable.
	/// </summary>
	BlueprintPure = 1 << 9,

	/// <summary>
	/// This function can be called from blueprint code and should be exposed to the user of blueprint editing tools.
	/// </summary>
	BlueprintCallable = 1 << 10,

	// /// <summary>
	// /// This function is used as the get accessor for a blueprint exposed property. Implies BlueprintPure and BlueprintCallable.
	// /// </summary>
	// BlueprintGetter = 1 << 11,

	// /// <summary>
	// /// This function is used as the set accessor for a blueprint exposed property. Implies BlueprintCallable.
	// /// </summary>
	// BlueprintSetter = 1 << 12,

	// /// <summary>
	// /// This function will not execute from blueprint code if running on something without network authority
	// /// </summary>
	// BlueprintAuthorityOnly = 1 << 13,

	// /// <summary>
	// /// This function is cosmetic and will not run on dedicated servers
	// /// </summary>
	// BlueprintCosmetic = 1 << 14,

	/// <summary>
	/// This function can be called in the editor on selected instances via a button in the details panel.
	/// </summary>
	CallInEditor = 1 << 15,

	// /// <summary>
	// /// Generate a field entry for the NotifyFieldValueChanged interface.
	// /// </summary>
	// FieldNotify = 1 << 16,

	// /// <summary>
	// /// This function must supply a _Validate implementation
	// /// </summary>
	// WithValidation = 1 << 17,

	// /// <summary>
	// /// This function is RPC service request
	// /// </summary>
	// ServiceRequest = 1 << 18,

	// /// <summary>
	// /// This function is RPC service response
	// /// </summary>
	// ServiceResponse = 1 << 19,
}

[AttributeUsage(AttributeTargets.Method)]
// ReSharper disable once InconsistentNaming
public class UFUNCTIONAttribute : Attribute
{
	public UFUNCTIONAttribute(params FuncSpecs[] specifiers)
	{
		foreach (var specifier in specifiers)
		{
			Specifiers |= specifier;
		}
	}

	public FuncSpecs Specifiers { get; }

	/// <summary>
	/// The name to display for this class, property, or function instead of auto-generating it from the name.
	/// </summary>
	public string? DisplayName;

	/// <summary>
	/// Specifies the category of the function when displayed in blueprint editing tools.
	/// </summary>
	public string? Category;

	/// <summary>
	/// Free-form metadata entries applied to the generated class, each in the form "Key=Value"
	/// (a bare "Key" is treated as "Key=true").
	/// </summary>
	public string[]? Meta;
}
