#pragma once
#include "CoreMinimal.h"

struct FSsMetaDataEntry;

/**
 * Engine-agnostic UFUNCTION specifier bits supplied by the C# layer.
 * <br/> See: SharpScript/Framework/Subclassing/UFunctionAttribute.cs FuncSpecs
 */
enum class ESsFunctionSpecifier : uint64
{
	// /** This function is designed to be overridden by a blueprint. Do not provide a body for this function;
	//  * the autogenerated code will include a thunk that calls ProcessEvent to execute the overridden body. */
	// BlueprintImplementableEvent = 1llu << 0,

	/** This function is designed to be overridden by a blueprint, but also has a native (C#) implementation.
     * The C# side writes a single method whose body is the default implementation; source-level calls to it
     * are redirected (via C# interceptors) to a virtual-dispatch entry that resolves any blueprint override. */
	BlueprintEvent = 1llu << 1,

	// /** This function is sealed and cannot be overridden in subclasses.
	//  * It is only a valid keyword for events; declare other methods as static or final to indicate that they are sealed. */
	// SealedEvent = 1llu << 2,

	/** This function is executable from the command line. */
	Exec = 1llu << 3,

	// /** This function is replicated, and executed on servers. Provide a body named [FunctionName]_Implementation
	//  * instead of [FunctionName]; the autogenerated code will include a thunk that calls the implementation method when necessary. */
	// Server = 1llu << 4,

	// /** This function is replicated, and executed on clients. Provide a body named [FunctionName]_Implementation
	//  * instead of [FunctionName]; the autogenerated code will include a thunk that calls the implementation method when necessary. */
	// Client = 1llu << 5,

	// /** This function is both executed locally on the server and replicated to all clients, regardless of the Actor's NetOwner. */
	// NetMulticast = 1llu << 6,

	// /** Replication of calls to this function should be done on a reliable channel.
	//  * Only valid when used in conjunction with Client, Server, or NetMulticast. */
	// Reliable = 1llu << 7,

	// /** Replication of calls to this function can be done on an unreliable channel.
	//  * Only valid when used in conjunction with Client, Server, or NetMulticast. */
	// Unreliable = 1llu << 8,

	/** This function fulfills a contract of producing no side effects, and additionally implies BlueprintCallable. */
	BlueprintPure = 1llu << 9,

	/** This function can be called from blueprint code and should be exposed to the user of blueprint editing tools. */
	BlueprintCallable = 1llu << 10,

	// /** This function is used as the get accessor for a blueprint exposed property. Implies BlueprintPure and BlueprintCallable. */
	// BlueprintGetter = 1llu << 11,

	// /** This function is used as the set accessor for a blueprint exposed property. Implies BlueprintCallable. */
	// BlueprintSetter = 1llu << 12,

	// /** This function will not execute from blueprint code if running on something without network authority. */
	// BlueprintAuthorityOnly = 1llu << 13,

	// /** This function is cosmetic and will not run on dedicated servers. */
	// BlueprintCosmetic = 1llu << 14,

	/** This function can be called in the editor on selected instances via a button in the details panel. */
	CallInEditor = 1llu << 15,

	// /** Generate a field entry for the NotifyFieldValueChanged interface. */
	// FieldNotify = 1llu << 16,

	// /** This function must supply a _Validate implementation. */
	// WithValidation = 1llu << 17,

	// /** This function is RPC service request. */
	// ServiceRequest = 1llu << 18,

	// /** This function is RPC service response. */
	// ServiceResponse = 1llu << 19,
};

ENUM_CLASS_FLAGS(ESsFunctionSpecifier);

/**
 * Expands the engine-agnostic UFUNCTION specifier bits + metadata onto a freshly created UFunction.
 */
class FSsFunctionSpecifiers
{
public:
	/**
	 * Apply the given specifier bits and metadata entries to Func.
	 * @param Func The generated UFunction being built (its FunctionFlags/metadata are mutated in place).
	 * @param SpecifierBits The raw C# FuncSpecs bit set to expand.
	 * @param MetaEntries Free-form metadata key/value entries to write verbatim (may be null).
	 * @param MetaCount Count of MetaEntries.
	 */
	static void Apply(UFunction* Func, uint64 SpecifierBits, const FSsMetaDataEntry* MetaEntries, int MetaCount);

	/**
	 * Whether the given raw C# FuncSpecs bit set marks the function as a blueprint-overridable event.
	 * Event functions are allowed to override a same-named base-class blueprint event.
	 * @param SpecifierBits The raw C# FuncSpecs bit set.
	 */
	static bool IsBlueprintEvent(uint64 SpecifierBits);
};
